// Image list for the gallery
const images = [
    { src: ".netlify/images?url=/images/_DSC3356.jpg", alt: "_DSC3356" },
    { src: ".netlify/images?url=/images/_DSC3993.jpg", alt: "_DSC3993" },
    { src: ".netlify/images?url=/images/_DSC4016.jpg", alt: "_DSC4016" },
    { src: ".netlify/images?url=/images/_DSC4095.jpg", alt: "_DSC4095" },
    { src: ".netlify/images?url=/images/_DSC4177.jpg", alt: "_DSC4177" },
    { src: ".netlify/images?url=/images/_DSC4278.jpg", alt: "_DSC4278" },
    { src: ".netlify/images?url=/images/_DSC4324.jpg", alt: "_DSC4324" },
    { src: ".netlify/images?url=/images/_DSC4533.jpg", alt: "_DSC4533" },
    { src: ".netlify/images?url=/images/_DSC4584.jpg", alt: "_DSC4584" },
    { src: ".netlify/images?url=/images/_DSC4719.jpg", alt: "_DSC4719" },
    { src: ".netlify/images?url=/images/_DSC4810.jpg", alt: "_DSC4810" },
    { src: ".netlify/images?url=/images/_DSC4813.jpg", alt: "_DSC4813" },
    { src: ".netlify/images?url=/images/_DSC4825.jpg", alt: "_DSC4825" },
    { src: ".netlify/images?url=/images/_DSC4836.jpg", alt: "_DSC4836" },
    { src: ".netlify/images?url=/images/_DSC4881.jpg", alt: "_DSC4881" },
    { src: ".netlify/images?url=/images/_DSC4892.jpg", alt: "_DSC4892" },
    { src: ".netlify/images?url=/images/_DSC4920.jpg", alt: "_DSC4920" },
    { src: ".netlify/images?url=/images/_DSC4929.jpg", alt: "_DSC4929" },
    { src: ".netlify/images?url=/images/_DSC5021.jpg", alt: "_DSC5021" },
    { src: ".netlify/images?url=/images/_DSC5055.jpg", alt: "_DSC5055" },
    { src: ".netlify/images?url=/images/_DSC5078.jpg", alt: "_DSC5078" },
    { src: ".netlify/images?url=/images/_DSC5121.jpg", alt: "_DSC5121" },
    { src: ".netlify/images?url=/images/_DSC5128.jpg", alt: "_DSC5128" },
    { src: ".netlify/images?url=/images/Bicycle Man.jpg", alt: "Bicycle Man" },
    { src: ".netlify/images?url=/images/Pipes.jpg", alt: "Pipes" }
];